### ISSUE TITLE
Request 有没有打算集成 表单验证器

### ISSUE THREAD

**Issue by Joycezhangw** [walkor/webman-framework#115]
Request 有没有打算集成 表单验证器。然后控制器验证，表单单独建立 `UserRequest`，控制器依赖注入。这样就把验证这块分离处理

**Comment by walkor** [comment]
不清楚你要具体怎么样的集成
目前webman最新版本支持控制器参数注入，可以设定参数及类型，框架会自动检测
https://www.workerman.net/doc/webman/controller.html#%E6%8E%A7%E5%88%B6%E5%99%A8%E5%8F%82%E6%95%B0%E7%BB%91%E5%AE%9A

更多验证器组件参考这里
https://www.workerman.net/doc/webman/components/validation.html
