### ISSUE TITLE
[BUG] Session cookie overriding all other cookies on first visit

### ISSUE THREAD

**Issue by mikeychowy** [walkor/webman-framework#22]
Currently on first visit to a page (session cookie doesn't exist yet), session cookie will ignore all other cookies set inside the  $_header['Set-Cookie'] array of Response class.

cookie set through convenience method (Set-Cookie key):
![image](https://user-images.githubusercontent.com/54876684/146823948-251dd00b-1374-4318-b70c-c2a893cfad41.png)

cookies deleted (simulating first visit):
![image](https://user-images.githubusercontent.com/54876684/146824185-6497fb39-a8a5-4358-ad5c-0235379188e4.png)

only session cookie is set:
![image](https://user-images.githubusercontent.com/54876684/146824263-21a7e611-15d7-414b-813b-c4ddcdcf5b0a.png)
![image](https://user-images.githubusercontent.com/54876684/146824382-569ac7b0-635e-4659-bc98-e6ee93ad1021.png)

current workaround (using set-cookie):
![image](https://user-images.githubusercontent.com/54876684/146824511-6b7b90a3-5fdb-462c-bf83-42aaccb51724.png)
![image](https://user-images.githubusercontent.com/54876684/146824555-97bac35f-dff7-4a3f-b606-cefe420ec195.png)
![image](https://user-images.githubusercontent.com/54876684/146824597-adf3d4c1-3cea-4c14-8158-92fc2ccd6c46.png)

How about setting the session cookie header using "set-cookie" key instead, so it doesn't conflict with convenience method key?
I would submit a pull request, but I can't seem to find where exactly you're setting the header for session cookie. If you could direct me to it I'd be happy to create PR.

**Comment by walkor** [comment]
I will fix it today.

**Comment by walkor** [comment]
Fixed, please upgrade workerman to 4.0.26 or higher.
`composer require workerman/workerman ^4.0.26`

**Comment by mikeychowy** [comment]
Thank you very much @walkor, will upgrade now, if this made it into production I'll try to negotiate with my company about donating monthly.

**Comment by walkor** [comment]
Great. Thank you very much for your kindness.
