### ISSUE TITLE
建议插件的Install.php检测机制。

### ISSUE THREAD

**Issue by ichynul** [walkor/webman-framework#43]
对于定义了多个命名空间的包，`key($autoload['psr-4'])`取到不可控。
除了我自己的代码，为了兼容`thinkphp`的一些依赖，我还定义了一个`think`命名空间。
```json
"autoload": {
        "psr-4": {
            "tpext\\myadmin\\": "src/",
            "think\\": "think/"
        },
        "files": [
            "src/helper.php"
        ]
    }
```
我使用本地git仓库作为依赖的时候取到的是第一个`tpext\myadmin`。
发布到`packgist`上面再用另外一台电脑安装测试，取到的是`think`（也许是排序过），就是这么邪门。
为了兼容，我只能两个命名空间都放个`Install.php`，其中`think`下面的是继承自真正的那个。
```php
<?php

namespace think;

class Install extends \tpext\myadmin\Install
{
}
```

现在的问题是，只要安装其他`thinkphp`相关的库[think-template/think-orm/think-cache]，因为里面都有`think`命名空间，
都匹配都我包里面的这个`think\Install`重新执行一遍。

建议不要用`key($autoload['psr-4'])`取一个，而是遍历数组。

**Comment by walkor** [comment]
直接发pr吧
