### ISSUE TITLE
自动重启的问题

### ISSUE THREAD

**Issue by miaotaizi** [walkor/webman-framework#6]
我在设置 `server.max_request` 这个配置的时候观察到一个现象, 当请求数到达  `server.max_request` 设置的数值触发重启条件时, 若浏览器未完全关闭 此时 `Webman\App::$_worker->connections` 永远不会变成 0 , 从而导致无法重启, 这是为何?

若生产环境触发重启条件但是重启总是不成功, 是不是表示会有内存溢出这类风险?

**Comment by walkor** [comment]
连接还在就关闭进程会不安全，因为关闭的时候连接上可能有数据正在发过来，导致请求失败。
如果你需要直接关闭可以先手动改下 vendor/workerman/webman-framework/src/App.php onMessage里的逻辑
